// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as IndexJs from "../dist/index.js";

function checkBindings(prim) {
  return IndexJs.checkBindings(prim);
}

Buntest.test("bun:test externals match @types/bun", done => {
  IndexJs.checkBindings({
    dir: "."
  }).then(result => {
    let errorCount = result.summary.errors;
    Buntest.expect(errorCount).toBe(0);
    done();
    return Promise.resolve();
  });
});

export {
  checkBindings,
}
/*  Not a pure module */
