// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";

Buntest.describe("bun test externals", () => {
  Buntest.test("basic expectation", () => {
    Buntest.expect(2).toBe(2);
  });
});

/*  Not a pure module */
